# Generated by Django 3.2.9 on 2022-07-18 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20220707_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstapp.category'),
        ),
    ]
