# Generated by Django 3.2.9 on 2022-07-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_customer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
