# Generated by Django 3.2.9 on 2022-07-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20220724_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='custom',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
